### PR TITLE
Fix base field provider interface generics

### PR DESCRIPTION
**Pull request by bonifacechacha**
Hi,

I have fixed the generic definition on the FieldProvider interface which initially 

1. was defined  with an incorrect type
2. not used in the method definitions

### CODE REVIEW

**Comment by alejandro-du** [comment]
Sorry, can you rebase so I can test and merge? Did you test your changes with the included demo app?

**Comment by bonifacechacha** [comment]
> 

Yes. So I have changed the java version for both the addon and demo to use java 11 since we are building using vaadin 23.

**Comment by bonifacechacha** [comment]
At first i included the changes for supporting java 11 instead of 1.8. But i have removed them to fix this pull request and I have created a different pull request for migrating the addon from 1.8 to 11.

**Comment by alejandro-du** [comment]
Thanks for the contribution!

**Pull request merged**
