### PR TITLE
Added a TreeGridCRUD Implementation which uses TreeGrid

### PR DESCRIPTION
**Pull request by bonifacechacha**

### CODE REVIEW

**Comment by alejandro-du** [comment]
@bonifacechacha thanks for your contribution. It seems there are some conflicts atm. Could you resolve them, please? (sorry if I caused them with recent commits).

**Comment by bonifacechacha** [comment]
> @bonifacechacha thanks for your contribution. It seems there are some conflicts atm. Could you resolve them, please? (sorry if I caused them with recent commits).

@alejandro-du , I have resolved the conflicts and pushed

**Comment by bonifacechacha** [comment]
@alejandro-du can you release another version with the most recent changes?

**Comment by alejandro-du** [comment]
I just released 5.1.0. Thanks a lot for your contribution and please let me know if it works. Building Vaadin projects hasn't been that smooth recently.

**Pull request merged**
